Add HPA Support to vmselect component
VictoriaMetrics/helm-charts pull request #172
Opened 2021-07-08 11:54 UTC by arnoldyahad

2021-07-09 07:18 UTC, f41gh7 commented
Thanks for PR, related issue https://github.com/VictoriaMetrics/helm-charts/issues/171

2021-07-11 19:26 UTC, tenmozes requested changes

2021-07-11 19:26 UTC, tenmozes commented on charts/victoria-metrics-cluster/values.yaml
> +    targetCPUUtilizationPercentage: 70
can we add section metrics here 
something like

```
metrics: []
```

and user can define own metric here like 
```
metrics:
  - type: Resource
    resource:
        name: cpu
        targetAverageUtilization: 60

2021-07-11 19:26 UTC, tenmozes commented on charts/victoria-metrics-cluster/templates/vmselect-hpa.yaml
> +  targetCPUUtilizationPercentage: {{ .Values.vmselect.horizontalPodAutoscaler.targetCPUUtilizationPercentage }}
can we add next property to config and use next to render it 
```
metrics:
{{ toYaml .Values.autoscaling.metrics | indent 4 }}
```

2021-07-11 19:29 UTC, tenmozes commented
@arnoldyahad thank for contribution please check my comments

2021-07-12 09:08 UTC, arnoldyahad commented
@f41gh7 This PR is not related to #171 
#171 is regarding HPA to vmagent, which is a bit more tricky since its a stateful set.
This pr is to enable HPA on vmselect component.

2021-07-12 19:47 UTC, tenmozes approved these changes
everything is perfect, thank you so much i will bump version and create release

2021-07-12 19:47 UTC, merged