Some improvements to Chart documentation
VictoriaMetrics/helm-charts pull request #542
Opened 2023-05-23 14:12 UTC by denisgolius

This PR contains: 
- adds some additional information about VM Cluster Chart
- adds some additional information about k8s-stack Chart

2023-05-23 19:34 UTC, hagen1778 commented on charts/victoria-metrics-cluster/README.md
> +> Note that this chart only installs VictoriaMetrics cluster components such as vminsert, vmselect and vmstorage. It will not create or configure metrics scraping. If you are looking for a chart to c
I think this is Chart Details. Lines 15-17 can be removed.

2023-05-24 14:25 UTC, zekker6 submitted a review, later dismissed

2023-05-24 14:34 UTC, tenmozes commented on charts/victoria-metrics-cluster/README.md
> +Note that this chart only installs VictoriaMetrics cluster components such as vminsert, vmselect and vmstorage. It will not create or configure metrics scraping. If you are looking for a chart to con
__Note__:  this chart installs VictoriaMetrics cluster components such as vminsert, vmselect and vmstorage. It doesn't create or configure metrics scraping. If you are looking for a chart to configure monitoring stack in cluster check out [victoria-metrics-k8s-stack chart](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack#helm-chart-for-victoria-metrics-kubernetes-monitoring-stack).

2023-05-24 14:34 UTC, tenmozes requested changes

2023-05-24 14:34 UTC, tenmozes commented on charts/victoria-metrics-cluster/README.md.gotmpl
> +Note that this chart only installs VictoriaMetrics cluster components such as vminsert, vmselect and vmstorage. It will not create or configure metrics scraping. If you are looking for a chart to con
as above

2023-05-24 19:41 UTC, tenmozes approved these changes

2023-05-24 19:41 UTC, merged

2023-05-24 19:42 UTC, tenmozes commented
@denisgolius thank you for contribution