Update to new HPA apiVersion, and allow specifying in values
VictoriaMetrics/helm-charts pull request #556
Opened 2023-06-06 12:14 UTC by ellie

1. Upgrade to new apiVersion. autoscaling/v2beta2 is no longer supported as of 1.26, and has been deprecated for a few versions now
2. Allow specifying the apiVersion in values. This is a fairly common pattern and will allow users to workaround this change.

Resolves #514

2023-06-06 12:47 UTC, k1rk requested changes
thanks for contribution @ellie 

instead of implementing this as parameter could you please use `.Capabilities.APIVersions.Has` check in helm template? this will be simpler for users of chart

2023-06-06 13:24 UTC, ellie commented
Sure! Just to point out though, if using `helm template`, the version will be fetched from just the local client, vs helm install/upgrade using the remote cluster version. Probably fine, but could cause confusion for some users

2023-06-06 14:11 UTC, k1rk approved these changes

2023-06-06 14:37 UTC, tenmozes commented
@ellie thanks for contribution

2023-06-06 14:37 UTC, merged

2023-06-06 14:41 UTC, tenmozes commented
the feature/fix should be available in 0.9.72 version

2023-06-06 14:41 UTC, atropos112 commented
> thanks for contribution @ellie 
> 
> instead of implementing this as parameter could you please use `.Capabilities.APIVersions.Has` check in helm template? this will be simpler for users of chart 

This is going to bite with ArgoCD, i would argue have the capabilities api version unless overwritten by variable not just that.

2023-06-06 22:13 UTC, b-a-t commented
> > thanks for contribution @ellie
> > instead of implementing this as parameter could you please use `.Capabilities.APIVersions.Has` check in helm template? this will be simpler for users of chart
> 
> This is going to bite with ArgoCD, i would argue have the capabilities api version unless overwritten by variable not just that.

@ellie righteously pointed out the issues with `helm template` usage, which is, basically what ArgoCD is using. I remember we addressed a similar problem with it in PSP detection in the chart with ArgoCD.

From other side I see(on older cluster) that ArgoCD supplies:

```
helm template . --name-template vm-cluster --namespace monitoring --kube-version 1.24 ... --api-versions autoscaling/v1 --api-versions autoscaling/v1/HorizontalPodAutoscaler --api-versions autoscaling/v2 --api-versions autoscaling/v2/HorizontalPodAutoscaler --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta1/HorizontalPodAutoscaler --api-versions autoscaling/v2beta2 --api-versions autoscaling/v2beta2/HorizontalPodAutoscaler ...
```

And
```
helm template . --name-template dev-vm --namespace monitoring --kube-version 1.25 ... --api-versions autoscaling/v1 --api-versions autoscaling/v1/HorizontalPodAutoscaler --api-versions autoscaling/v2 --api-versions autoscaling/v2/HorizontalPodAutoscaler --api-versions autoscaling/v2beta2 --api-versions autoscaling/v2beta2/HorizontalPodAutoscaler ...
```

So, that conditioning may work if matching is done on exact capability paths...

2023-06-07 05:34 UTC, k1rk commented
Argocd supplies capabilities to helm template based on data gathered from your cluster, so it should be fine with argocd